-- 코드를 입력하세요
SELECT FA.FOOD_TYPE,REST_INFO.REST_ID,REST_INFO.REST_NAME, FA.FAVORITES
FROM REST_INFO, (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC) AS FA
WHERE REST_INFO.FOOD_TYPE = FA.FOOD_TYPE AND REST_INFO.FAVORITES = FA.FAVORITES
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC