-- 코드를 입력하세요
# SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
# FROM ANIMAL_INS INS LEFT OUTER JOIN ANIMAL_OUTS OUTS
# ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
# WHERE OUTS.SEX_UPON_OUTCOME != INS.SEX_UPON_INTAKE

SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
FROM ANIMAL_INS, ANIMAL_OUTS 
WHERE ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
AND ANIMAL_OUTS.SEX_UPON_OUTCOME != ANIMAL_INS.SEX_UPON_INTAKE
 