-- 코드를 입력하세요
SELECT PRODUCT_CODE, (PRICE * AMOUNT) AS SALES
FROM PRODUCT, (
SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMOUNT
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID
) AS O
WHERE PRODUCT.PRODUCT_ID = O.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC
