-- 코드를 입력하세요
SELECT FOOD_PRODUCT.PRODUCT_ID,FOOD_PRODUCT.PRODUCT_NAME, SUM(FOOD_PRODUCT.PRICE * FOOD_ORDER.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT, FOOD_ORDER
WHERE FOOD_PRODUCT.PRODUCT_ID = FOOD_ORDER.PRODUCT_ID
AND YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
GROUP BY FOOD_PRODUCT.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FOOD_PRODUCT.PRODUCT_ID ASC

