-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT AS P, DOCTOR AS D, APPOINTMENT AS A
WHERE A.MDDR_ID = D.DR_ID
AND A.PT_NO = P.PT_NO
AND A.APNT_CNCL_YN = 'N'
AND A.APNT_YMD LIKE '2022-04-13%'
ORDER BY A.APNT_YMD ASC