-- 코드를 입력하세요 식8950 김19000 국2900 과1950
SELECT FOOD_PRODUCT.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT,(SELECT 
CATEGORY
, MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY = '과자'
OR CATEGORY = '국'
OR CATEGORY = '김치'
OR CATEGORY = '식용유'
GROUP BY CATEGORY
) AS PR
WHERE FOOD_PRODUCT.CATEGORY = PR.CATEGORY AND FOOD_PRODUCT.PRICE = PR.MAX_PRICE
ORDER BY PRICE DESC